### ISSUE TITLE
test statistics?

### ISSUE THREAD

**Issue by kkmann** [spgarbet/tangram#55]
Hey,

I am having trouble finding the functionality to include test statistics in the standard tables (as in the current CRAN version). Has that feature been dropped?

**Comment by spgarbet** [comment]
The feature has not been dropped. I'm also woefully behind in CRAN release.

Does `test=TRUE` work?

Also, I just added (and it's a work in progress) the ability to add `test=function(row, col, style, ...) {}` for the edge version.

**Comment by kkmann** [comment]
Thanks, that worked for me, maybe it was a documentation glitch (i was working from master). Still a big fan, I still need to dig through how to define my own layout but I just love the principled approach.
