### ISSUE TITLE
Removed from CRAN

### ISSUE THREAD

**Issue by sciatro** [spgarbet/tangram#60]
It seems that tangram has been removed from [CRAN](https://cran.r-project.org/package=tangram):

> Package ‘tangram’ was removed from the CRAN repository.
>
> Formerly available versions can be obtained from the archive.
>
> Archived on 2020-04-09 as check problems were not corrected despite reminders.
>
> Please use the canonical form https://CRAN.R-project.org/package=tangram to link to this page.

Thanks for all the hard work on this interesting package. It's exciting to see work blending the 'Harrell-verse' and grammatical / tidyverse.

**Comment by spgarbet** [comment]
Thank you for letting me know. I can assure you that I have received *zero* notifications or reminders. This is very disappointing.

I'm looking over the package and the problem appears to be R6 documentation via Roxygen. They changed how it's parsed and checked. It's very irritating. I'm trying to figure out a way around it.

**Comment by sciatro** [comment]
Thanks for looking into it. Sorry I don't have any knowledge of R packaging to contribute to a fix.



Also, it looks like one of the links in the README is broken by these changes

> For an example using Rmarkdown, see example.html

I see the links at the top of the read me got removed. As an alternative the old knitted examples can be linked out of the history, e.g.

https://htmlpreview.github.io/?https://raw.githubusercontent.com/spgarbet/tangram/50f81ac47dc34e942df3f3f1324dcb7259acd95f/inst/doc/example.html

**Comment by spgarbet** [comment]
Thanks. I'll get that patched up in Issue #61. 

Otherwise tag v0.7.1 has been pushed to tangram.

The root of the problem was my institution's spam filters gobbled up the notifications. Ugh.
