### ISSUE TITLE
README fda-example link broken

### ISSUE THREAD

**Issue by sciatro** [spgarbet/tangram#61]
From the README

> See fda-example.html for some examples--don't be put off by size of the examples.

Which points to http://htmlpreview.github.io/?https://github.com/spgarbet/tg/blob/master/vignettes/fda-example.html (.../tg/..., not tangram) is broken. This looks independent of #60 changes.

It's a bit of a dirty fix but looks like the knitted HTML can be linked out of the history at: https://htmlpreview.github.io/?https://github.com/spgarbet/tangram/blob/1ea7046a8c78b73b091cc2dfcc5e33389bc2bfbd/inst/doc/fda-example.html

**Comment by spgarbet** [comment]
Due to Issue #60 I had to do a quick push of the current package state. Tinytex was broken on my local system, so I stripped these out and pushed. I am working on putting it all back. Now I don't have to create a ticket for it! So this is the current focus of effort.

**Comment by spgarbet** [comment]
e566b4b99eceb2be2911b7d9ea9c9af2c4291749
