### ISSUE TITLE
multiple comparison correction support

### ISSUE THREAD

**Issue by conge** [spgarbet/tangram#71]
Hi Shawn,

I find this package very handy to create tables for reports, especially it provides statistical tests and reports p-values back.

But my question is, are the reported p-values corrected for the multiple comparison problem? if it is, what method was used?

Thanks,

Yang

**Comment by spgarbet** [comment]
Assuming you question refers to the default rmisc transform the answer is no correction is applied. 

The rmisc transform is our departments recommended exploratory summary of data. The *p*-values are simply to look for something 'worthy of further investigation'. 

Also a transform has no knowledge of the broader number of methods being applied. There is support in the hmisc module for specifying ones own statistical model to generate *p*-values. You're free to do whatever method you desire.

**Comment by spgarbet** [comment]
I spoke with Frank Harrell and these *p*-values have caused more confusion and aren't worthy of reporting in general. He's now recommending that they be removed entirely.
