### ISSUE TITLE
UTF+8 issue with rtf function, "N=" duplicated

### ISSUE THREAD

**Issue by jr1234567** [spgarbet/tangram#73]
Hello 
Many thanks for this great package
I noticed that the rtf() function seems to add an extra  "N=" string in table header of generated rtf file,  as exemplified in the following example:

```
a <-   tangram('drug~bili["%4.03f"]+albumin+stage::Categorical[1]+protime+sex["%4.06f"]+age+spiders[1]', 
         data=pbc,
         pformat = 5,
         style="lancet",
         caption = "Table Lancet Style",
         relsize=-2,
         capture_units=FALSE,
         footnote = ""
 ) %>%  del_col(3)

  rtf(  a, file="file.rtf")
  
```

**Comment by spgarbet** [comment]
rtf gets the least love. This should fix it. Let me know if that works. Also, I noticed the lancet style has issues with the centered decimal. Do you see this on your end?

**Comment by jr1234567** [comment]
Many thanks. The duplicated "N=" is resolved.
Indeed there are other issues:
-With the lancet style the duplicated decimal gives a weird "Â" 
-With the Hmisc style, the "/" is missing, whereas the "*" are duplicated
-With the nejm style, the dash is replaced by "0â€”"

**Comment by spgarbet** [comment]
These are all  UTF+8 character handling. I need to look into what's required for this in RTF. The RTF spec was designed before unicode. I changed the title. Hopefully there's just some escaping required.

**Comment by spgarbet** [comment]
Found this: https://stackoverflow.com/questions/66275158/specify-utf-8-character-encoding-in-rtf-the-text-in-utf-8-format-is-correctly

**Comment by spgarbet** [comment]
https://www.oreilly.com/library/view/rtf-pocket-guide/9781449302047/ch01.html#unicode_in_rtf

I experimented with this. I can write a transformer I think. 

There's also some Markdown not handled properly after the refactor. In particular, bold.

**Comment by spgarbet** [comment]
I've realigned this with the recent refactor. Should be able to move onto UTF+8 handling next.

**Comment by spgarbet** [comment]
Try this version.

**Comment by jr1234567** [comment]
- OK for the nejm style which appears to be rendered correctly
-  With the lancet style : not OK: the centered decimal is rendered as Â·
- With the hmisc style: not OK: the * are now missing

**Comment by spgarbet** [comment]
The hmisc "*" missing is intended. It should be bold now. 

I'll check on the lancet. That was working on my side. The centered decimal is in the lower code space of UTF-8 which of course requires different handling.

**Comment by spgarbet** [comment]
I've duplicated the Â· on a different machine. Trying to solve.

**Comment by spgarbet** [comment]
It works for me now with all three cases. The only thing I see odd is the left column in 'nejm' is centered instead of left justified.

**Comment by jr1234567** [comment]
new tests:
- hmisc style : * and / are not rendered.
- lancet style : everything seems ok
-  nejm style : everything seems ok

**Comment by spgarbet** [comment]
Why do you want the "*" rendered? It's a bold directive. I switched it to be consistent with the other styles and made it a bold.

**Comment by jr1234567** [comment]
Ah OK !  I misunderstood that,. 
I only mentioned them for consistency reason as that they do appear as such when viewing a table in Rstudio
This is indeed way better not to have them  
The / is useful though for numerator / denominator

**Comment by spgarbet** [comment]
I think this leaves rtf in good shape now.

**Comment by jr1234567** [comment]
Everything is beautiful 
Many thanks for this great job
